name: Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
        - scheme: Woods (iOS)
          destination: generic/platform=iOS
        - scheme: Woods (macOS)
          destination: generic/platform=macOS
        - scheme: Woods (watchOS)
          destination: generic/platform=watchOS

    steps:
    - uses: actions/checkout@v3
    - name: Build ${{ matrix.scheme }}
      run: xcodebuild -scheme "${{ matrix.scheme }}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

# TODO: Run tests
